# Generated by Django 4.2.7 on 2023-12-08 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_expense_created_at_expense_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expense_images/'),
        ),
        migrations.CreateModel(
            name='ExpenseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='expense_images/')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.expense')),
            ],
        ),
    ]
